version: '3.9'

services:
  orders-eventstore:
    image: ghcr.io/eventstore/eventstore:21.10.2-alpha-arm64v8
    restart: always
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: orders-eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: orders-eventstore-volume-logs
        target: /var/log/eventstore

  orders-raven:
    image: ravendb/ravendb:5.4.4-ubuntu.20.04-arm64v8
    ports:
      - "8080:8080"
      - "38888:38888"
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_License_Eula_Accepted=true
    volumes:
      - type: volume
        source: orders-raven-volume-data
        target: /opt/RavenDB/Server/RavenData

  payments-eventstore:
    image: ghcr.io/eventstore/eventstore:21.10.2-alpha-arm64v8
    restart: always
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1123:1113"
      - "2123:2113"
    volumes:
      - type: volume
        source: payments-eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: payments-eventstore-volume-logs
        target: /var/log/eventstore

  payments-raven:
    image: ravendb/ravendb:5.4.4-ubuntu.20.04-arm64v8
    ports:
      - "8081:8080"
      - "38889:38888"
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_License_Eula_Accepted=true
    volumes:
      - type: volume
        source: payments-raven-volume-data
        target: /opt/RavenDB/Server/RavenData

  rabbitmq:
    image: arm64v8/rabbitmq:3-management
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - 'rabbitmq:/var/lib/rabbitmq'

volumes:
  orders-eventstore-volume-data:
  orders-eventstore-volume-logs:
  orders-raven-volume-data:
  payments-eventstore-volume-data:
  payments-eventstore-volume-logs:
  payments-raven-volume-data:
  rabbitmq: